version: '3.8'

services:
  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8080:80"
  php:
    build: images/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '0000'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/Users/fp/Documents/Dev/Template/mySQL'